### ISSUE TITLE
Please take a look

### ISSUE THREAD

**Issue by abelykh0** [dcrespo3d/zx-spectrum-tetris#1]
Can you please allow "Issues" on your fork https://github.com/dcrespo3d/ZX-ESPectrum-Wiimote, see accepted answer here https://softwareengineering.stackexchange.com/questions/179468/forking-a-repo-on-github-but-allowing-new-issues-on-the-fork. Your fork is so far ahead of the original, I would like to contribute to it rather than https://github.com/rampa069/ZX-ESPectrum

**Comment by dcrespo3d** [comment]
Hello, I have allowed Issues on ZX-ESPectrum-Wiimote. Thanks for your interest in it :-)

**Comment by abelykh0** [comment]
Thanks!
